// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import AppleProductTypes
import PackageDescription

let package = Package(
  name: "LibreNiim",
  platforms: [
    .iOS("15.2")
  ],
  products: [
    .iOSApplication(
      name: "LibreNiim",
      targets: ["AppModule"],
      bundleIdentifier: "com.talaviram.libreniim",
      teamIdentifier: "7P7G2A8U54",
      displayVersion: "0.1",
      bundleVersion: "1",
      appIcon: .asset("AppIcon"),
      accentColor: .presetColor(.cyan),
      supportedDeviceFamilies: [
        .pad,
        .phone,
      ],
      supportedInterfaceOrientations: [
        .portrait,
        .landscapeRight,
        .landscapeLeft,
        .portraitUpsideDown(.when(deviceFamilies: [.pad])),
      ],
      capabilities: [
        .bluetoothAlways(purposeString: "The app uses Bluetooth to connect with label printers")
      ],
      appCategory: .productivity
    )
  ],
  dependencies: [
    .package(url: "https://github.com/manolofdez/AsyncBluetooth", "1.11.0"..<"2.0.0")
  ],
  targets: [
    .executableTarget(
      name: "AppModule",
      dependencies: [
        .product(name: "AsyncBluetooth", package: "AsyncBluetooth")
      ],
      path: ".",
      swiftSettings: [
        .enableUpcomingFeature("BareSlashRegexLiterals")
      ]
    )
  ]
)
